import math

infinity = math.inf

# Fixation detection (Savitzky-Golay)
SG_WINDOW_LENGTH = 50  # ms
SG_DEGREE = 2

# Acceptable thresholds
ACCEPTABLE_NUM_CALIBRATIONS = (4, infinity)
ACCEPTABLE_AVG_VALIDATION_SCORES = (0.0, 0.6)
ACCEPTABLE_MAX_VALIDATION_SCORES = (0.0, 2.0)
ACCEPTABLE_VALIDATION_ERRORS = ["GOOD", "FAIR"]
ACCEPTABLE_DATA_LOSS_RATIOS = (0.0, 0.10)
ACCEPTABLE_RECORDING_DURATIONS = (600_000, 7_200_000)
